name: Build and test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run fmt:check --workspaces
    - run: npm run build:all
    - run: npm run test --workspaces
